### ISSUE TITLE
No login Code

### ISSUE THREAD

**Issue by DannyEss** [toblum/ESPTeamsPresence#25]
Hey, I want to build my Presence Light but I can't get a code in "Start device login". 

![grafik](https://user-images.githubusercontent.com/80511142/156748535-72df366f-38da-4648-bab8-02822196b480.png)

**Comment by toblum** [comment]
Hi @DannyEss,

unfortunately I wasn't able to answer for some weeks because I broke my hand. Is this still an issue? 

To see what happens, it would be great to have a look at the serial console of the device when it's plugged in to a PC.

Greetings
Tobias

**Comment by brian-inksmith** [comment]
@toblum I am getting the same thing as @DannyEss 
On the console it says 
`[HTTPS] Connection refused`

The fix was to comment the disablecertcheck
`//#define DISABLECERTCHECK 1 `

**Comment by riraosan** [comment]
Hi @DannyEss 

Here is my log, I am not able to get the code because I am not able to communicate over SSL due to lack of SRAM.
Are you in the same situation as me?
If there is only about 90KB of heap memory left when the program is executed, the SSL communication process will fail.

![2022-08-09_222915](https://user-images.githubusercontent.com/47518585/183660460-626727fe-0099-4c88-98c7-9f164d737796.png)
![2022-08-09_222939](https://user-images.githubusercontent.com/47518585/183660811-bc6d2439-3c45-4265-a19a-0f8fd92422f7.png)

**Comment by icaputo** [comment]
I had the same issue, fixed using the default client ID (and not my own)
Client-ID:  3837bbf0-30fb-47ad-bce8-f460ba9880c3

**Comment by fabianocattaneo** [comment]
I'm having the same issue (no code) even if I am using the default cliend ID.

Any suggestion?

**Comment by toblum** [comment]
@fabianocattaneo Do you have access to the device console? Or the Azure AD Enterprise apps? This would be helpful.

Also please have a look here: https://github.com/toblum/ESPTeamsPresence/issues/23#issuecomment-1452553793

**Comment by fabianocattaneo** [comment]
Indeed I really don't know what happened, a recompile and reflash fixed the issue and it is working ok right now.

**Comment by toblum** [comment]
@fabianocattaneo Great! Sometimes it just happens that way with software. :-)
