### ISSUE TITLE
Compile on ESP8266

### ISSUE THREAD

**Issue by fmatray** [toblum/ESPTeamsPresence#26]
Hello,
I would like to compile it for a Wemos D1 mini PRO (ESP8266).

I tried but I have several errors with library dependencies.

I added those lines in platform.ini, as suggested by PlatformIO.
```
[env:d1_mini_pro]
platform = espressif8266
board = d1_mini_pro
```

I had this first error about missing headers, followed by several other ones.
```
Compiling .pio/build/d1_mini_pro/lib759/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
Compiling .pio/build/d1_mini_pro/lib759/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
src/main.cpp:16:10: fatal error: HTTPClient.h: No such file or directory
```

I have errors with following libraries : 
#include <HTTPClient.h>     => corrected by ESP8266HTTPClient
#include <ESPmDNS.h>      => corrected byt ESP8266mDNS
**#include "SPIFFS.h"            => Can't find an ESP8266 version
#include "ESP32_RMT_Driver.h" => same**

Do you have any idea how to do, please?

Thanks

**Comment by toblum** [comment]
Hi @fmatray,

unfortunately I had broken my hand and wasn't able to answer here for some weeks. So sorry for the late reply.

I'm afraid this won't work on an ESP8266 without a bigger rewrite, if at all, because the code makes use of both core of the microcontroller (ESP8266 only has one core).

Greetings
Tobias
